name: Deploy Docker and Run Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 10 * * *'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
    - name: Build and Push Docker image
      run: |
        docker build -t scab1001/flask-app:latest .
        docker push scab1001/flask-app:latest
      env:
        DOCKER_BUILDKIT: 1


  run_unit_tests:
    needs: build_and_deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run unit tests and echo output
      run: |
        python -m unittest discover -s . 2>&1 | tee test_results.txt
    - uses: actions/upload-artifact@v2
      with:
        name: unittest-results
        path: test_results.txt
