name: Docker Deploy and Run Tests

on:
  push:
    branches:
      - main  # Adjust this as necessary for your workflow

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
    - name: Build and Push Docker image
      run: |
        docker build -t scab1001/flask-app:latest .
        docker push scab1001/flask-app:latest
      env:
        DOCKER_BUILDKIT: 1

    # Optionally, you can also start the Docker container here
    # and expose it on a specific port if your tests require
    # interacting with a live instance

  run_unit_tests:
    needs: build_and_deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify your Python version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run unit tests
      run: python -m unittest discover -s tests
